parameters:
#    ation_blog.example.class: Ation\Bundle\BlogBundle\Example

services:
#    ation_blog.example:
#        class: %ation_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
